[package]
name = "rust_modules_packages_crates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://crates.io/search?q=regex%20
regex = "1.6.0"